name: marnager
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.2
  firebase_storage: 13.0.3
  http: ^1.5.0
  intl: ^0.20.2

  cupertino_icons: ^1.0.8
  fluid_dropdown_input: ^1.0.0
  image_picker: ^1.1.2
  permission_handler: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  


flutter:
  assets:
    - assets/images/
  uses-material-design: true


